# -*- coding: utf-8 -*-
"""JSON_Search.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e5kf-SG4yMdRWkZ2ShlRb1SDiojtJP9m
"""

import json

from google.colab import drive
drive.mount('/content/drive')

f = open('/content/drive/MyDrive/Web Archiving stuff/AoT_Metadata/4028targets.json')
data = json.load(f)
f.close()

new_data = []
counter = 0

for target in data:
    if any('.org' in url_list for url_list in target['urls']) and \
      (target['crawl_frequency'] == 'WEEKLY' or target['crawl_frequency'] == 'MONTHLY') and \
      target['description'] != '':
      new_data.append(target)
      if counter<=2:
        print(str(counter+1) + ': ' + str(target))
      counter += 1

with open('/content/drive/MyDrive/Web Archiving stuff/AoT_Metadata/4028_output.json', "w") as write_file:
    json.dump(new_data, write_file, indent=2)

print('...')
print(str(counter-2) + ': ' + str(new_data[-3]))
print(str(counter-1) + ': ' + str(new_data[-2]))
print(str(counter) + ': ' + str(new_data[-1]))
print('\nData written to file')
print('Total number of targets in JSON file: ' + str(counter))

