# -*- coding: utf-8 -*-
"""JSON_Visualise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kr8wE4JeQy2eM4-mfM6bP6tMwXXJa1qk
"""

import json
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_json('/content/drive/MyDrive/Web Archiving stuff/AoT_Metadata/4028targets.json')
df

df['crawl_start_date'].count()

#df.groupby(['crawl_frequency'])['crawl_frequency'].count().plot.bar()
df['crawl_frequency'].value_counts().plot.bar()

def to_1D(series):
  return pd.Series([x for the_list in series for x in the_list])

to_1D(df['subject_ids']).value_counts().nlargest(10).plot.bar()

to_1D(df['collection_ids']).value_counts().nlargest(10).plot.bar()

df2 = df

df2['month_crawl_start_date'] = pd.to_datetime(df2['crawl_start_date'], errors='coerce').dt.strftime('%Y-%m')

df2 = df2[(df2['month_crawl_start_date'] > "2022-02-07") & (df2['month_crawl_start_date'] < "2022-12-31")]

grouped_df = df2.groupby('month_crawl_start_date').size().to_frame("count").reset_index()

grouped_df.plot(kind='bar', x='month_crawl_start_date', y='count')

df3 = df

df3['month_crawl_start_date'] = pd.to_datetime(df3['crawl_start_date'], errors='coerce').dt.strftime('%Y')

df3 = df3[pd.to_datetime(df3['month_crawl_start_date'], errors='coerce').dt.strftime('%Y')<'2022']

grouped_df = df3.groupby('month_crawl_start_date').size().to_frame("count").reset_index()

grouped_df.plot(kind='bar', x='month_crawl_start_date', y='count')